version: '3.8'

services:
  app:
    build:
      context: ./  # Replace with the path to your application code
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: postgres
    depends_on:
      - postgres
    ports:
      - "8000:8080" 

volumes:
  pg_data:
